#!/usr/bin/env bash
#
#/ command: yum-rpm:install: "Install the specified Rerun modules Yum repository RPM"
#
#/ usage: rerun yum-rpm:install [ --version <1.0>] [ --release <1>] 
#
#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option variables: VERSION RELEASE

# Read module function library.
. $RERUN_MODULE_DIR/lib/functions.sh || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Error handling
# ---------------
# * Trap calls `rerun_die` with standard message.
# * Exit upon command errors or accessing unset variables.
#   * See [set](http://ss64.com/bash/set.html)
trap 'rerun_die $? "*** command failed: yum-rpm:install. ***"' ERR
set -o nounset -o pipefail

# Parse the command options.
[[ -r $RERUN_MODULE_DIR/commands/install/options.sh ]] && {
    . $RERUN_MODULE_DIR/commands/install/options.sh || rerun_die "Failed loading options parser."
    rerun_options_parse "$@"
}


# ------------------------------
# Your implementation goes here.
# ------------------------------

TMPDIR=$(mktemp -d)

rerun github:get-download --owner rerun-modules --repository rerun-modules --file rerun-modules-yum-repo-${VERSION}-${RELEASE}.noarch.rpm --output ${TMPDIR}/rerun-modules-yum-repo-${VERSION}-${RELEASE}.noarch.rpm
rerun rpm:upgrade --package-file ${TMPDIR}/rerun-modules-yum-repo-${VERSION}-${RELEASE}.noarch.rpm

rm -rf ${TMPDIR}

exit $?

# Done
